name: Hub Config Validation (R)

# Validates the hub's config files when a pull request changes them and posts
# the result on that pull request. Added with:
#
#   hubCI::use_hub_github_action("validate-config")

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'hub-config/**'
      - '!**README**'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-hub-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: hubverse-org/hubverse-actions/validate-config@v2
